services:
  gowhatsapp-worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL_MODE: ${DATABASE_SSL_MODE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASE: ${REDIS_DATABASE}
      REDIS_POOL_SIZE: ${REDIS_POOL_SIZE}
      REDIS_MIN_IDLE_CONNS: ${REDIS_MIN_IDLE_CONNS}
      REDIS_DIAL_TIMEOUT: ${REDIS_DIAL_TIMEOUT}
      REDIS_READ_TIMEOUT: ${REDIS_READ_TIMEOUT}
      REDIS_WRITE_TIMEOUT: ${REDIS_WRITE_TIMEOUT}
      REDIS_IDLE_TIMEOUT: ${REDIS_IDLE_TIMEOUT}
      REDIS_MAX_CONN_AGE: ${REDIS_MAX_CONN_AGE}
      REDIS_QUEUE_NAME: ${REDIS_QUEUE_NAME}
      REDIS_QUEUE_PROCESSING_TIMEOUT: ${REDIS_QUEUE_PROCESSING_TIMEOUT}
      REDIS_QUEUE_RETRY_DELAY: ${REDIS_QUEUE_RETRY_DELAY}
      REDIS_QUEUE_MAX_RETRIES: ${REDIS_QUEUE_MAX_RETRIES}
      REDIS_QUEUE_BLOCKING_POP_TIMEOUT: ${REDIS_QUEUE_BLOCKING_POP_TIMEOUT}
      REDIS_QUEUE_BATCH_SIZE: ${REDIS_QUEUE_BATCH_SIZE}
      REDIS_CONSUMER_GROUP: ${REDIS_CONSUMER_GROUP}
      REDIS_CONSUMER_NAME: ${REDIS_CONSUMER_NAME}
      REDIS_STREAM_MAX_LEN: ${REDIS_STREAM_MAX_LEN}
      WHATSAPP_BASE_URL: ${WHATSAPP_BASE_URL}
      WHATSAPP_AUTH: ${WHATSAPP_AUTH}
      ENABLE_AUTH: ${ENABLE_AUTH}
      AUTH_TYPE: ${AUTH_TYPE}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
      DASHBOARD_REALM: ${DASHBOARD_REALM}
      API_KEY: ${API_KEY}
      API_KEY_HEADER: ${API_KEY_HEADER}
      WORKER_CONCURRENCY: ${WORKER_CONCURRENCY}
      WORKER_BATCH_SIZE: ${WORKER_BATCH_SIZE}
      WORKER_POLL_INTERVAL: ${WORKER_POLL_INTERVAL}
      WORKER_MAX_RETRIES: ${WORKER_MAX_RETRIES}
      RATE_LIMIT_MIN_MESSAGES: ${RATE_LIMIT_MIN_MESSAGES}
      RATE_LIMIT_MAX_MESSAGES: ${RATE_LIMIT_MAX_MESSAGES}
      RATE_LIMIT_DELAY_MIN: ${RATE_LIMIT_DELAY_MIN}
      RATE_LIMIT_DELAY_MAX: ${RATE_LIMIT_DELAY_MAX}
      RATE_PROFILE: ${RATE_PROFILE}
      RATE_DELAY_MEAN_MS: ${RATE_DELAY_MEAN_MS}
      RATE_DELAY_JITTER_MS: ${RATE_DELAY_JITTER_MS}
      RATE_BURST_LIMIT: ${RATE_BURST_LIMIT}
      RATE_COOLDOWN_SECONDS: ${RATE_COOLDOWN_SECONDS}
      TYPING_DELAY_MIN: ${TYPING_DELAY_MIN}
      TYPING_DELAY_MAX: ${TYPING_DELAY_MAX}
      NATURAL_BREAK_INTERVAL: ${NATURAL_BREAK_INTERVAL}
      NATURAL_BREAK_DURATION_MIN: ${NATURAL_BREAK_DURATION_MIN}
      NATURAL_BREAK_DURATION_MAX: ${NATURAL_BREAK_DURATION_MAX}
      HEALTH_CHECK_INTERVAL: ${HEALTH_CHECK_INTERVAL}
      STUCK_MESSAGE_TIMEOUT: ${STUCK_MESSAGE_TIMEOUT}
      LOG_LEVEL: ${LOG_LEVEL}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
    volumes:
      - logs:/app/logs

volumes:
  logs:
    driver: local
