services:
  gowhatsapp-worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - logs:/app/logs

volumes:
  logs:
    driver: local
